import { Item } from 'src/app/Models/item';
export const ItemList: Item[] =[ 
      { 
        index: 1,
        title: 'Shoes',
        price: 2000,
        isDiscount: true,
        discountPercent: 2,
        description: 'xyz',
        
      },
      {
        index: 2,
        title: 'Shirts',
        price: 1599,
        isDiscount: false,
        discountPercent: 2,
        description: 'xyz',
      },
      {
        index: 3,
        title: 'Watch',
        price: 12000,
        isDiscount: false,
        discountPercent: 2,
        description: 'xyz',
      },
      {
        index: 4,
        title: 'Belt',
        price: 1000,
        isDiscount: true,
        discountPercent:5,
        description: 'xyz',
      },
      {
        index: 5,
        title: 'Shoes',
        price: 3000,
        isDiscount: false,
        discountPercent: 4,
        description: 'xyz',
      },
      {
        index: 6,
        title: 'Shirts',
        price: 2999,
        isDiscount: true,
        discountPercent: 4,
        description: 'xyz',
      },
      {
        index: 7,
        title: 'Watch',
        price: 30000,
        isDiscount: false,
        discountPercent: 2,
        description: 'xyz',
      },
      {
        index: 8,
        title: 'Shorts',
        price: 900,
        isDiscount: true,
        discountPercent: 2,
        description: 'xyz',
      },
      {
        index: 9,
        title: 'Shorts',
        price: 800,
        isDiscount: false,
        discountPercent: 2,
        description: 'xyz',
      },
      {
        index: 10,
        title: 'Shirts',
        price: 2000,
        isDiscount: true,
        discountPercent: 2,
        description: 'xyz',
      }
]